# Generated by Django 4.2.7 on 2023-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Título')),
                ('author', models.CharField(max_length=256, verbose_name='Autor')),
                ('year_publication', models.DateField(verbose_name='Año de publicación')),
            ],
            options={
                'verbose_name': 'Libro',
            },
        ),
    ]
